### PR TITLE
Add iframe resizing

### PR DESCRIPTION
**Pull request by nmonterroso**
@kensnyder @gbenson-wikia @drsnyder @kollyjr 

This PR moves the `IframeResize` quill module from Wikia's private repo to the core `quill-image-resize-module` repo. This fulfills the ask in kensnyder/quill-image-resize-module#4 for resizing videos.

`IframeResize` leverages the functionality of `ImageResize` pretty heavily. Whenever an iframe receives the `mouseenter` event the `IframeResize` module creates a transparent image that's placed over the iframe. Any resizing/realignment done on that proxy image is then mirrored onto the iframe, and the image is then re-positioned on top of the iframe. To the end user there's no difference in the experience of resizing iframes and images.

 To achieve this I had to extract the alignment code from the `Toolbar` module into `AlignmentHelper` since the iframe code needs to use that same functionality. I also did some directory shuffling so the iframe and image classes weren't all in the same directory. I also updated the demo page with a sample video.

Please let me know if there are any changes you'd like me to make! I think this functionality will be super useful to `quill-image-resize-module` (though maybe it'll be in need of a name change 😉 )

TODO:
- [x] update README with `iframeResize`

### CODE REVIEW

**Comment by seandearnaley** [comment]
good work on this, I happened to catch it whilst working on image resize modifications this evening... I was testing your PR and it works pretty well the only issue I have found so far is that backspace delete key throws an error-- I checked the code it seems it's because the Quill.find call is looking for the proxy image blot rather than the underlying video element.. not sure how hard it is to fix.

**Comment by nmonterroso** [comment]
Ah good catch! I changed this on the `ImageResize` side to make sure the blot is truthy before issuing the `deleteAt` call, and on the `IframeResize` side to delete any actively selected iframes in a207c92

**Comment by seandearnaley** [comment]
@nmonterroso thanks for addressing that, I use the image resize plugin in a project but I have to modify it and I'm quite interested in other approaches.. this is very useful to me.   I do have another issue that may be a bit more challenging, I happen to use the style attribute rather than width/height, specifically because I've had trouble using scale percentages for width's, I need to have a full width button, that goes 100% because some of my content is reflowable--- I can normally make the necessary modifications, but your proxy image is absolutely positioned, if I set it to 100% it becomes 100% of the window and not the images quill container...  I wonder is there another way to position the proxy image relative to the container.

**Comment by nmonterroso** [comment]
@seandearnaley that seems like an interesting problem but I think it's out of scope for the use case in the core library (since as you say you've modified `ImageResize` to suit your needs). 

That said, though, if you setup a demo where I can see the issue you're describing I could probably take a look.

**Comment by seandearnaley** [comment]
@nmonterroso  definitely related to image sizing, I mean it'd be nice to be able to scale images with percentages, in this current configuration I can only use pixel values and any percentage values break the sywtem... if there is any content with for example width = 100%, the image proxy doesn't work.  That's without modifying the image resize plugin...   I can set up a code pen for you later today..

**Comment by seandearnaley** [comment]
hey @nmonterroso , sorry for the delay I've only just had a chance to codepen this for you...I've taken style property out of the mix, just using percentages in the regular width attribute... I'm using your latest minified plugin with quill 1.2.6.   I've embedded an iframe but I've set the width attribute to 100%--  scale kinda works with image resize and doesn't glitch out I think because it doesnt use the absolute image proxy like your PR but I'm not sure... the delta json doesn't save the scaled percent width but there is graphical issues, it seems this doesn't support percent widths.

https://codepen.io/SDearnaley/pen/BZqEEq

**Comment by bubach** [comment]
After trying the image resizer I was thinking it might be a functionality that should have it's own repo or even be part of the core, and not bundled directly to the image resizing?

Other suggestions would be number and position of drag points, mainly useful for resizing tables and such in all directions where aspect ratio isn't an issue.

And finally, settings for resize stategy - like snapping to grid or based on preset number of css classes instead of just supporting width & height attributes in px.

**Comment by guateandrew** [comment]
hey @nmonterroso, love that you pulled this together and trying to integrate in a scoped package. Though after several hours of trying cannot seem to have it play nice with my webpack

** your index.js**
export { IframeResize } from './iframe/IframeResize';
export { default as ImageResize } from './image/ImageResize'; 
**my index.js***
import * as QuillPlugins from '@[private]/quill-image-resize-module'
console.log(QuillPlugins.ImageResize) // OK
console.log(IframeResize) // undefined

I thought maybe webpack was only exporting the named default from index.js but even the following returned undefined.

** your index.js**
import IframeResize from  './iframe/IframeResize';
import ImageResize from './image/ImageResize';
export default {
  IframeResize,
  ImageResize
}

Most likely I am not understanding how this gets bundled into webpack ... the documentation for webpack is so patchy.

**Comment by nmonterroso** [comment]
@guateandrew I hadn't noticed this, but I am seeing some issues using it that way. It should definitely work the way you're trying to use it, so I'll take a look.

**Comment by nmonterroso** [comment]
@guateandrew so I definitely messed up the export of IframeResize. This has been fixed in 42587ed.

A quick working demo of console.log is available [here](https://github.com/nmonterroso/quill-image-resize-module-demo)

**Comment by nmonterroso** [comment]
We decided to completely redo the functionality provided by this module with built-in support for iframes and easier extensibility in [`quill-blot-formatter`](https://github.com/Fandom-OSS/quill-blot-formatter)

**Pull request closed without merging**
